-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 14:04:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema education
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema education
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `education` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `education` ;

-- -----------------------------------------------------
-- Table `education`.`corsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `education`.`corsi` (
  `id_corso` INT NOT NULL AUTO_INCREMENT,
  `nome_corso` VARCHAR(255) NULL DEFAULT NULL,
  `posti_disponibili` INT NULL DEFAULT NULL,
  `nome_materia` VARCHAR(255) NULL DEFAULT NULL,
  `id_materia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_corso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `education`.`materie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `education`.`materie` (
  `id_materia` INT NOT NULL,
  `nome_materia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
